# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s ="Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [4]:
x="The diameter of {planet} is {diameter} kilometer".format(planet="Earth",diameter=12742)
print(x)

The diameter of Earth is 12742 kilometer


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
array=np.ones(10)*5
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [11]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
import numpy as np
x =  np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [17]:
import pandas as pd
data = [[10,"Rajesh"],[20,"deepak"],[30,"Ravi"]]
df = pd.DataFrame(data, columns=['Numbers','Student Names'])
df

Numbers Student Names
0       10        Rajesh
1       20        deepak
2       30          Ravi

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
import pandas as pd
from dateutil.parser import parse
date_series = pd.Series(['Jan 2023', 'Feb 2023'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('1' + d))
print(result)

Original Series:
0    Jan 2023
1    Feb 2023
dtype: object

New dates:
0   2023-01-01
1   2023-02-01
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists = pd.DataFrame(lists, columns=['S.no','Student Names','Marks'])
lists

S.no Student Names  Marks
0     1           aaa     22
1     2           bbb     25
2     3           ccc     24